version: "3.0"

# # USING RENDER DB
volumes:
  postgres_data:
    driver: local

services:
  IF YOU WANT TO RUN DB LOCAL CHANGE THE ENVIRONMENT AND UNCOMMENT THIS
  postgresql:
    image: "postgres:15.10"
    ports:
      - "127.0.1.1:5438:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
      # USE THESE VARIABLES IN ENVS/LOCAL
    # networks:
    #   notes_net:
    #     aliases:
    #       - postgresql
    restart: always

#   # THIS alllows to create a container but communication between container seems to have a problem
#   notes:
#     build:
#       context: "."
#     image: "danielsv0606/note:1"
#     ports:
#       - "5710:5000"
#     environment:
#       - POSTGRES_HOSTNAME=dpg-ct3s6ut6l47c73f4h45g-a.oregon-postgres.render.com
#       - POSTGRES_USER=notes_db_user
#       - POSTGRES_PASSWORD=kT7KD42fMvnKyGCNNcFbZPmT7WPOuW2R
#       - POSTGRES_DB=notes_database_gorn
#     networks:
#       notes_net:
#         aliases:
#           - notes
#     restart: always

# networks:
#   notes_net:
